# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efa9624a6bdf6bfe9cae15be3c8c4e3ebb9ade555d1c3379816d7699a3d2cc416ea16fb296b3ce305b3bd1a626eb140c88e3f5808b99b932ba362ef8bbb15e09

test:
  secret_key_base: fe51ba3c4d6c32038d806c4356c6dc0a9e3c4da5c52dc7c3895cbcc1b4bb622e50d4af9031ec9570770570b666f9882023abcfdf21bf537fb3b6b4dc89c3c486

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
